export const SUBMISSION_STATUS = {
  SUBMITTED: "SUBMITTED",
  AWAITING_REVIEW: "AWAITING_REVIEW",
  UNDER_REVIEW: "UNDER_REVIEW",
  REJECTED: "REJECTED",
  RESUBMITTED: "RESUBMITTED",
  APPROVED: "APPROVED",
  CI_RUNNING: "CI_RUNNING",
  CI_PASSED: "CI_PASSED",
  CI_FAILED: "CI_FAILED",
  REVIEWER_APPROVED: "REVIEWER_APPROVED",
  REVIEWER_REJECTED: "REVIEWER_REJECTED",
  AWAITING_MANAGER_APPROVAL: "AWAITING_MANAGER_APPROVAL",
  MANAGER_APPROVED: "MANAGER_APPROVED",
  MANAGER_REJECTED: "MANAGER_REJECTED",
  MERGED: "MERGED",
  DEPLOYED: "DEPLOYED",
  DEPLOYMENT_IN_PROGRESS: "DEPLOYMENT_IN_PROGRESS",
  DEPLOYMENT_SUCCESSFUL: "DEPLOYMENT_SUCCESSFUL",
  DEPLOYMENT_FAILED: "DEPLOYMENT_FAILED",
};

export const REVIEW_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  CHANGES_REQUESTED: "CHANGES_REQUESTED",
};
